<?php
/**
 * @file
 * Emvideo youtube module.
 */

/**
 * Implements hook_emvideo_parse().
 */
function emvideo_youtube_emvideo_parse($url) {
  $matches = array();
  if (preg_match('@^(?:https?\:\/\/)?(?:www\.)?youtu(?:|\.be|be\.com)(\/watch|\/embed|\/v/|\/)+((.*)?[\&\?]v=)?([^"\& ]+)@i', $url, $matches)) {
    $hosts = array(
      'i.ytimg.com',
      'i1.ytimg.com',
      'i2.ytimg.com',
      'i3.ytimg.com',
      'i4.ytimg.com',
      'img.youtube.com',
    );

    $host = $hosts[array_rand($hosts)];

    return array(
      'source' => 'http://www.youtube.com/embed/' . $matches[4],
      'provider' => 'youtube',
      'snapshot' => 'http://' . $host . '/vi/' . $matches[4] . '/0.jpg',
    );
  }

  return FALSE;
}

/**
 * Implements hook_emvideo_emcode().
 */
function emvideo_youtube_emvideo_emcode($params) {
  $output = FALSE;
  if ($params['provider'] == 'youtube') {
    // Use Youtube's new iframe embedding method.
    $output = '<iframe width="'. $params['width'] .'" height="'. $params['height'] .'" src="'. $params['source'] .'" frameborder="0" allowfullscreen></iframe>';
  }
  return $output;
}
